server:
  port: 8001
spring:
  application:
    name: springcloud-rest-provider-8001
eureka:
  client:
    service-url:
      #这个地方和服务的一致，需要注册地址
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: dept-provider
    #访问路径可以显示IP
    prefer-ip-address: true
    info:
      app.name: springcloud-study-provider
      company.name: www.code.java.com
      build.artifactId: $project.artifactId$
      build.version: $project.version$
